- name: Install postgresql packages
  package: name={{ item }}
           state=present
  with_items:
    - postgresql
    - postgresql-client
  tags:
    - download

- name: Create postgresql-xs systemd service
  template: backup=yes
            src=postgresql-xs.service
            dest=/etc/systemd/system/postgresql-xs.service
            owner=root
            group=root
            mode=0644

- name: Create postgres data directory
  file: path=/library/pgsql-xs
        owner=postgres
        group=postgres
        mode=0700
        state=directory

- name: make sure that the en_US locale is enabled
  lineinfile: dest=/etc/locale.gen
              regexp='^# en_US.UTF8'
              line='en_US.UTF8 UTF8'
  when: ansible_distribution == "Debian"

- name: generate the selected locales
  command: /usr/sbin/locale-gen
  when: ansible_distribution == "Debian"

- name: Discover if the postgresql database data directory has already been created
  stat: path="/library/pgsql-xs/base"
  register: p
   
- name: Initialize the postgres db
  command:  su - postgres -c "/usr/lib/postgresql/9.4/bin/initdb -E 'UTF-8' --lc-collate='en_US.UTF-8' --lc-ctype='en_US.UTF-8' -D /library/pgsql-xs"
            creates=/library/pgsql-xs/pg_hba.conf
  when: p.stat.exists is defined and not p.stat.exists

- name: Configure postgres 
  template: backup=yes
            src=postgresql.conf.j2
            dest=/library/pgsql-xs/postgresql.conf
            owner=postgres
            group=postgres
            mode=0640

- name: Disable stock postgresql service
  service: name=postgresql
           enabled=no
  when: postgresql_enabled

- name: Enable postgresql service
  service: name=postgresql-xs
           enabled=yes
  when: postgresql_enabled

- name: Add postgresql to service list
  ini_file: dest='{{ service_filelist }}'
            section=postgresql
            option='{{ item.option }}'
            value='{{ item.value }}'
  with_items:
    - option: name
      value: postgresql
    - option: description
      value: '"PostgreSQL is a powerful, open source object-relational database system."'
    - option: installed
      value: "{{ postgresql_install }}"
    - option: enabled
      value: "{{ postgresql_enabled }}"
