- name: Install sugar-stats required packages
  yum: name=$item
       state=installed
  with_items:
    - sugar-stats-server
    - active-document
    - restful-document
    - python-xappy

- name: Create sugar-stats directory tree
  file: path=$item
        owner=sugar-stats
        group=sugar-stats
        mode=0755
        state=directory
  with_items:
    - /library/sugar-stats/
    - /library/sugar-stats/rrd
    - /library/sugar-stats/users

- name: Copy sugar-stats config file
  template: src=sugar-stats.conf.j2
            dest=/etc/sugar-stats.conf
            owner=sugar-stats
            group=sugar-stats
            mode=0644

- name: Enable sugar-stats service
  service: name=sugar-stats-server
           enabled=yes
          
- include: statistics-consolidation.yml 
