- name: download wondershaper ajenti plugin
  pip: name=http://"{{ xsce_download_url }}"/ajenti-plugin-wondershaper-0.3.tar.gz
        extra_args="--download-cache {{ pip_packages_dir }}"

- name: install wondershaper from local download directory
  pip: name=ajenti-plugin-wondershaper
       extra_args="--no-index --find-links=file://{{ pip_packages_dir }}"

#  notify:
#    - restart ajenti service
