dependencies:
   - { role: ejabberd }
   - { role: httpd }
   - { role: postgresql }
   - { role: moodle }
   - { role: idmgr }
   - { role: sugar-stats }
   - { role: iiab }
   - { role: ajenti }
   - { role: munin }
   - { role: monit }
   - { role: portal }
   - { role: activity-server }   
