dependencies:
   - { role: ejabberd, tags: ['olpc','ejabberd','core'] }
   - { role: httpd, tags: ['services','httpd','core'] }
   - { role: postgresql, tags: ['services','postgresql','core'] }
   - { role: moodle, tags: ['olpc','moodle','core'] }
   - { role: idmgr,  tags: ['olpc','idmgr','core'] }
   - { role: sugar-stats, tags: ['olpc','sugar-stats','core'] }
   - { role: authserver,  tags: ['services','authserver','core'] }
   - { role: ajenti, tags: ['services','ajenti','core'] }
   - { role: munin, tags: ['services','munin','core'] }
   - { role: monit, tags: ['services','monit','core'] }
   - { role: portal, tags: ['services','portal','core'] }
   - { role: activity-server, tags: ['olpc','activity-server','core'] }   
