---
# The values here are default local variables.
gui_wan_iface: "unset"
gui_static_wan_ip: "unset"
gui_desired_network_role: Gateway
wondershaper_dspeed: "4096"
wondershaper_upspeed: "1024"
host_ssid: "XSCE"
host_wifi_mode: g
host_channel: 6
host_wireless_n: False
host_country_code: US
driver_name: nl80211
network_config_dir: /etc/network/interfaces.d
xsce_network_mode: "Gateway"
dns_jail_enabled: False
