---
# The values here are default local variables.
gui_wan_iface: "unset"
gui_static_wan_ip: "unset"
wondershaper_dspeed: "4096"
wondershaper_upspeed: "1024"
host_ssid: "XSCE"
host_wifi_mode: g
host_channel: 6
host_wireless_n: False
host_country_code: US
capture_enabled: False
redirect_url: http//{{ xsce_hostname }}.{{ xsce_domain }}/redirect.php
