dependencies:
   - { role: sugar-stats, tags: ['olpc','sugar-stats','tools'] }
   - { role: ajenti, tags: ['services','ajenti','tools'] }
   - { role: munin, tags: ['services','munin','tools'] }
   - { role: monit, tags: ['services','monit','tools'] }
