- name: Install idmgr packages
  yum: name=${item}
       state=installed
  with_items:
   - ds-backup-server
   - idmgr
   - xinetd
   - xs-rsync
   - incron

- name: Configure idmgr
  template: src=${item.src}
            dest=${item.dest}
            owner=root
            group=root
            mode=${item.mode}
  with_items:
    - { src: 'idmgr', dest: '/etc/idmgr.conf', mode: '0644' }
    - { src: 'idmgr.service.j2', dest: '/etc/systemd/system/idmgr.service', mode: '0755'}

- name: Configure ds-backup
  command: /etc/sysconfig/olpc-scripts/setup.d/ds-backup
          creates=/etc/incron.d/ds-backup.conf

- name: Configure idmgr sqlite db
  command: /etc/sysconfig/olpc-scripts/setup.d/idmgr
           creates=/home/idmgr/identity.db

- name: Configure xs-rsync
  command: /etc/sysconfig/olpc-scripts/setup.d/xs-rsync
          creates=/etc/xinetd.d/xs-rsyncd

- name: Copy idmgr init script 
  command: /bin/cp /etc/init.d/idmgr /usr/libexec/idmgr.init
          creates=/usr/libexec/idmgr.init

- name: Enable idmgr service
  service: name=$item
           enabled=yes
           state=started
  with_items:
    - idmgr
    - xinetd

#idmgr needs an extra step
- name: Enable ejabberd service
  file: src=/etc/systemd/system/idmgr.service
        dest=/etc/systemd/system/multi-user.target.wants/idmgr.service
        owner=root
        group=root
        state=link


