- hosts: 127.0.0.1
  user: root
  connection: local
  vars:
  - watchdog: [ sshd,idmgr,ejabberd,httpd,postgresql,squid ]
  vars_files:
  - vars/default_vars.yml
  tasks:
#    - include: tasks/xo.yml
#      when: ansible_distribution_version == "13"
#    - include: tasks/install-xs.yml
    - include: tasks/idmgr.yml
#    - include: tasks/dhcpd.yml
    - include: tasks/monit.yml
#    - include: tasks/gateway.yml
#    - include: tasks/network.yml
#    - include: tasks/sysctl.yml
#    - include: tasks/named.yml
    - include: tasks/avahi.yml
    - include: tasks/sugar-stats.yml
    - include: tasks/ejabberd.yml
    - include: tasks/postgresql.yml
#    - include: tasks/pathagar.yml
