# By the time we get here we should have ka-lite of some version
# And the systemd unit files should be defined

- name: Disable kalite server
  service: name=kalite-serve
           enabled=no
           state=stopped
  when: not kalite_enabled

- name: Enable kalite server
  service: name=kalite-serve
           enabled=yes
           state=started
  async: 900
  poll: 5
  when: kalite_enabled

# Since Fedora 18 we don't have a separate unit fiile for kalite-cron

- name: Disable kalite cron server
  service: name=kalite-cron
           enabled=no
           state=stopped
  when: not kalite_cron_enabled and is_F18

- name: Enable kalite cron server
  service: name=kalite-cron
           enabled=yes
           state=started
  when: kalite_cron_enabled and is_F18
