dependencies:
   - { role: sugar-stats, tags: ['olpc','sugar-stats','tools'], when: sugar-stats_install }
#   - { role: ajenti, tags: ['services','ajenti','tools'], when: ajenti_install }
   - { role: munin, tags: ['services','munin','tools'], when: munin_install }
   - { role: monit, tags: ['services','monit','tools'], when: monit_install }
   - { role: vnstat, tags: ['services','vnstat','tools'], when: vnstat_install }
   - { role: xovis, tags: ['services','xovis','tools'], when: xovis_install }
   - { role: awstats, tags: ['services','awstats','tools'], when: awstats_install }
