- name: Install httpd required packages
  package: name={{ item }}
       state=present
  with_items:
    - httpd
    - php

- name: Install packages for console
  package: name={{ item }}
       state=present
  with_items:
    - mod_ssl
    - mod_authnz_external
    - pwauth

- name: Install packages for cmdsrv
  package: name={{ item }}
       state=present
  with_items:
    - gcc
    - gcc-c++
    - php-devel
    - php-pear
    - python-devel
    - python-pip
    - zeromq3-devel
    - cracklib-python
    - redhat-rpm-config
#        - zeromq3

#	pip install pyzmq  - didn't use the installed zmq rpm and the target zmq 4, not 3, for which there is no rpm.

- name: Download zeromq and python binding
  pip: name=pyzmq
       extra_args="--download {{ pip_packages_dir }}"

- name: Install zeromq and python binding
  pip: name=pyzmq
       extra_args="--no-index --find-links=file://{{ pip_packages_dir }}"

- name: Set the pear download_dir
  shell: "pear config-set download_dir {{ xsce_dir }}"

- name: Download php binding for zeromq
  shell: yes '' | pecl download zmq-beta

- name: Install php binding for zeromq
  shell: pecl install -f zmq*tgz
  args:
    creates: "{{ phplib_dir }}/modules/zmq.so"

- name: Download speedtest-cli
  pip: name=speedtest-cli
       extra_args="--download {{ pip_packages_dir }}"

- name: Install speedtest-cli
  pip: name=speedtest-cli
       extra_args="--no-index --find-links=file://{{ pip_packages_dir }}"

- name: Create admin-console directory
  file: path={{ item }}
        mode=0700
        owner=root
        group=root
        state=directory
  with_items:
    - "{{ cmdsrv_path }}"
    - "{{ cmdsrv_path }}/scripts"

- name: Set permissions on sqlite db
  file: dest="{{ cmdsrv_path }}/{{xsce_cmdsrv_dbname }}"
        mode=0600
        owner=root
        group=root
        state=touch
