- name: Install Fedora specifc packages
  package: name={{ item }}
           state=present
  with_items:
   - mtd-utils

- name: Install optional exFAT packages for Fedora
  shell: yum --enablerepo=rpmfusion-free-updates install exfat-utils fuse-exfat
  when: exFAT_enabled == "True"

- name: Disable updating ejabberd on Fedora
  shell: sed -i -e '/^enabled=/a exclude=ejabberd' {{ item }}
  with_items:
    - /etc/yum.repos.d/fedora.repo
    - /etc/yum.repos.d/fedora-updates.repo
    - /etc/yum.repos.d/fedora-updates-testing.repo
