- name: Create /opt/schoolserver/xsce
  file: path={{ xsce_dir }}
        owner=root
        group=root
        mode=0755
        state=directory

- name: Create /opt/schoolserver/yum-packages
  file: path={{ yum_packages_dir }}
        owner=root
        group=root
        mode=0755
        state=directory

- name: Create /opt/schoolserver/pip-packages
  file: path={{ pip_packages_dir }}
        owner=root
        group=root
        mode=0755
        state=directory

- name: Create /opt/schoolserver/downloads
  file: path={{ downloads_dir }}
        owner=root
        group=root
        mode=0755
        state=directory

- name: Create various library directories
  file: path={{ item }}
        owner=root
        group=root
        mode=0755
        state=directory
  with_items:
    - /library/downloads/zims
    - /library/downloads/rachel
    - /library/working/zims
    - /library/working/rachel

- name: Create olpc-scripts directory
  file: path={{ item }}
        owner=root
        group=root
        mode=0755
        state=directory
  with_items:
    - /etc/sysconfig/olpc-scripts/
    - /etc/sysconfig/olpc-scripts/setup.d/installed/

