- name: Disable systemd-networkd.service
  service: name=systemd-networkd.service
           enabled=no
  when: not is_F18

- name: Mask systemd-networkd.service
  shell: 'systemctl mask systemd-networkd'
  when: not is_F18

- name: Disable systemd-hostnamed.service
  service: name=systemd-hostnamed.service
           enabled=no
  when: not is_F18

- name: Mask systemd-networkd.service
  shell: 'systemctl mask systemd-hostnamed'
  when: not is_F18

- name: Disable dbus-org.freedesktop.hostname1.service
  service: name=dbus-org.freedesktop.hostname1
           enabled=no
  when: not is_F18

- name: Mask dbus-org.freedesktop.hostname1.service
  shell: 'systemctl mask dbus-org.freedesktop.hostname1'
  when: not is_F18

- name: Disable network.service
  service: name=network
           enabled=no

- name: Mask network.service
  shell: 'systemctl mask network.service'

# Network Manager starts this if needed
- name: Disable wpa_supplicant
  service: name=wpa_supplicant
           enabled=no

- name: Disable tmp.mount
  service: name=tmp.mount
           enabled=no

- name: Mask tmp.mount
  shell: 'systemctl mask tmp.mount'

- name: Remove tmpfs for /tmp
  lineinfile: dest=/etc/fstab
              regexp='/tmp'
              state=absent
