- name: workaround F23 install yum deps!!!
  shell: dnf install -y python-urlgrabber pyxattr yum-metadata-parser
  when: ansible_distribution == "Fedora" and ansible_distribution_version|int <= 23

- name: workaround F22 install yum from Fedora 23 for arm!!!
  shell: dnf install -y https://kojipkgs.fedoraproject.org//packages/yum/3.4.3/506.fc23/noarch/yum-3.4.3-506.fc23.noarch.rpm
  when: ansible_distribution == "Fedora" and ansible_machine == "armv7l" and ansible_distribution_version|int == 22

- name: install yum if it has been dropped from our distribution -- Fedora 22+ uses dnf!!!
  shell: dnf install -y yum
  when: ansible_distribution == "Fedora" and ansible_distribution_version|int <= 24

- name: Install yum packages
  yum: name={{ item }}
       state=present
  with_items:
   - yum-utils
   - createrepo
   - libselinux-python
  tags:
    - download

- name: Create local yum repo
  shell: createrepo {{ yum_packages_dir }}

- name: Install local repo file.
  template: dest=/etc/yum.repos.d/xsce-local.repo
            src=local.repo
            owner=root
            mode=0644

- name: Install common packages
  yum: name={{ item }}
       state=present
  with_items:
   - acpid
   - mlocate
   - rsync
   - htop
   - python-passlib
   - usbmount
   - net-tools
   - openssh-server
   - sudo
   - syslog
   - logrotate
   - xml-common
   - make
   - tar
   - unzip
   - bzip2
   - i2c-tools
   - bridge-utils
   - usbutils
   - hostapd
   - wpa_supplicant
   - wget
   - openssl   #FC 18 does not supply, but pear requires
   - linux-firmware # grab wifi firmware
  tags:
    - download

#- name: Update common packages
#  yum: name={{ item }}
#       state=latest
#  with_items:
#   - NetworkManager
#   - bash
#   - iptables
#   - vim-minimal # ejabberd erlang does not update this properly
#   - dbus-glib   # NM does not update this properly
#   - glibc # CVE-2015-7547
#  tags:
#    - download

# instuctions state to start with a fully updated system before starting, stop using
# ansible as a crutch for developers not following the directions and taking short-cuts

#- name: If version of Network manager has changed, subsequent nmcli commands will fail,restart now
#  service: name=NetworkManager
#           state=restarted
#  when: not installing
# the above should use a handler - all reboots should wait until all 
# mods are preformed

- name: Install optional exFAT packages for CentOS
  shell: yum --enablerepo=li-nux-ro install exfat-utils fuse-exfat
  when: exFAT_enabled == "True" and ansible_distribution == "CentOS"
