- name: Disable firewalld service
  service: name=firewalld
           enabled=no
           state=stopped
- name: Install iptables services
  template: src=${item.src}
            dest=${item.dest}
            owner=root
            group=root
            mode=0755
  with_items:
    - { src: "gateway/iptables-xs" , dest: "/etc/sysconfig/olpc-scripts/iptables-xs" }
    - { src: "gateway/ip6tables-xs" , dest: "/etc/sysconfig/olpc-scripts/ip6tables-xs" }
    - { src: "gateway/iptables-config" , dest: "/etc/sysconfig/iptables-config" }
    - { src: "gateway/iptables.service" , dest: "/etc/systemd/system/iptables.service" }

