- name: Install munin package
  yum: name=$item
       state=present
  with_items:
    - munin
    - munin-node

- name: Copy munin config file
  template: src=templates/munin/munin.conf.j2
            dest=/etc/munin/munin.conf
            owner=root
            group=root
            mode=0644

- name: Create admin user
  htpasswd: path=/etc/munin/munin-htpasswd
            name=admin
            password=munindxs
            create=yes
            state=present

- name: Enable munin-node service
  service: name=munin-node
           enabled=yes



