# use these as a tag a release at a point in time
new_gui_version: 2
new_menu_version: 2

# These entries should never be changed in this file.
# These are defaults for boolean routines
new_squid_cache: 0
ansbile1: True
new_menu: False
installing: False
exFAT_enabled: False
no_NM_reload: False
has_WAN: False
wireless_lan_present: False
udev_needs_patch: False
strict_networking: False
xsce_demo_mode: False
gw_active: False
gui_static_wan: False
has_internet_connection: False
is_F18: False
is_F20: False
is_F21: False
is_F22: False
is_F23: False
is_F24: False
is_F25: False

# Set default for discovered hardware
driver_name: nl80211
rpi_model: none
xo_model: none
rtc_id: none

# Set defaults for discovery process as strings
wifi1: "not found-1"
wifi2: "not found-2"
discovered_wan_iface: "none"
discovered_lan_iface: "none"
discovered_wireless_iface: "none"
xsce_wireless_lan_iface: "none"
xsce_lan_iface: "none"
xsce_wan_iface: "none"
device_gw: "none"
has_ifcfg_gw: "none"
has_wifi_gw: "none"
ap_device: "none"
device_gw2: ""

# WiFi
ssid: XSCE
hostapd_wait: 10
gui_port: 80
