# These are defaults for routines, these entries should never be changed in this file.
installing: False
exFAT_enabled: False

#Set defaults for discovery process
discovered_wan_iface: "none"
discovered_lan_iface: "none"
discovered_wireless_iface: "none"
xsce_wireless_lan_iface: "none"
xsce_lan_iface: "none"
xsce_wan_iface: "none"
device_gw: "none"
has_ifcfg_gw: "none"
has_WAN: False
no_NM_reload: False

#Set default for discovered hardware
wifi1: "not found"
wifi2: "not found"
wireless_lan_present: False
driver_name: nl80211
wifi_id: none
rpi_model: none
xo_model: none
rtc_id: none
ssid: XSCE
hostapd_wait: 10
