---
# Create a smbuser
#

- name: create smb user
  user: name="{{ smbuser }}" shell=/sbin/nologin password="{{ smbpassword }}"

- name: create the public folder
  file: dest="{{ shared_dir }}" owner="{{ smbuser }}" group="{{ smbuser }}" mode=777 state=directory

# Install and configure samba server (requires ports 137, 138, 139, 445 open).
- name: Ensure Samba-related packages are installed.
  yum: pkg={{ item }} state=installed
  with_items:
  - samba
  - samba-client
  - samba-common
  - cifs-utils
  tags:
    - samba

- name: put our smb.conf in place
  template: src=smb.conf.j2 dest=/etc/samba/smb.conf
  notify: restart smb

- name: Ensure Samba is running and set to start on boot.
  service: name=smb state=started enabled=yes
  tags: 
    - samba

- name: Ensure nmb is running and set to start on boot.
  service: name=nmb state=started enabled=yes
  tags: 
    - samba
