- name: Disable firewalld service
  service: name=firewalld
           enabled=no

- name: Use larger hammer to disable firewalld (2 symbolic links involved)
  shell: "systemctl disable firewalld.service"

- name: Mask firewalld service
  shell: 'systemctl mask firewalld'
  ignore_errors: yes
  when: not installing

- name: Stop firewalld service
  service: name=firewalld
           state=stopped
  ignore_errors: yes
  when: not installing

- name: Remove iptables.service file from /etc
  file: path=/etc/systemd/system/iptables.service 
        state=absent

- name: Remove iptables-xs.service file from /etc
  file: path=/etc/systemd/system/iptables-xs.service 
        state=absent

- name: Install iptables service package
  package: name=iptables-services
           state=installed
  tags:
    - download

- name: Install iptables services
  template: src={{ item.0 }}
            dest={{ item.1 }}
            owner='root'
            group='root'
            mode={{ item.2 }}
  with_items:
   - { 0: 'iptables-config', 1: '/etc/sysconfig/iptables-config', 2: '0644' }
