- name: Create home for content on portal page
  file: path={{ item }}
        mode=0755
        owner=apache
        group=apache
        state=directory
  with_items:
    - /library/content

- name: enable mod_rewrite
  apache2_module: name=rewrite

- include: xs-portal.yml
- include: alt-home.yml

- include: home-page.yml
  when: gui_desired_home_url is defined

- name: Default to /admin when first installed
  set_fact:
     xsce_home_url: '/admin'
  when: xsce_home_url == ""

- name: Install home page and content config file
  template: src={{ item }}
            dest=/etc/apache2/sites-available/
            owner=root
            group=root
            mode=0644
  with_items:
            - content_dir.conf
            - xsce-home-page.conf
  when: not installing

- name: enable the pages
  file: path=/etc/apache2/sites-enabled/{{ item }}
        src=/etc/apache2/sites-available/{{ item }} 
        state=link
  with_items:
      - content_dir.conf
      - xsce-home-page.conf
  notify: restart apache

