- name: gui_static_wan
  set_fact:
    wan_ip: dhcp
    gui_static_wan_ip: undefined
  when: gui_static_wan is defined and gui_static_wan == "False"

- name: Using GUI_STATIC info
  set_fact:
    wan_ip: "{{ gui_static_wan_ip }}"
    wan_netmask: "{{ gui_static_wan_netmask }}"
    wan_gateway: "{{ gui_static_wan_gateway }}"
    wan_nameserver: "{{ gui_static_wan_nameserver }}"
  when: gui_static_wan_ip != "unset" and gui_static_wan_ip != "undefined" and gui_static_wan is defined 

# need to add this field in the GUI
# we need to have an interface name for ifcfg-WAN to be able to change gateway the DEVICE from the gui.
- name: Using GUI_WAN info
  set_fact:
    user_wan_iface: "{{ gui_wan_iface }}"
  when: gui_wan_iface != "unset"

# should make the GUI buttons the last call
- name: Checking xsce_wan_enabled
  set_fact:
    user_wan_iface: "none"
  when: 'not xsce_wan_enabled'

# gui wants LanController # keeps ifcfg-WAN but onboot=no
# Note for macaddr4 had_gw becomes gw_device
# the change over might be a little bumpy ATM. 
- name: Setting GUI wants LanController
  set_fact:
    device_gw: "none"
    user_wan_iface: "none"
  when: gui_desired_network_role is defined and gui_desired_network_role == "LanController"

# single interface vars/ users would need to set xsce_wan_enabled False and set 
# user_lan_iface = <device> for the same effect.
- name: Setting user_lan_iface for LanController for single interface
  set_fact:
     user_lan_iface: "{{ discovered_wan_iface }}" 
  when: discovered_wan_iface != "none" and num_lan_interfaces == "0" and gui_desired_network_role is defined and gui_desired_network_role == "LanController"

# override with user_wan_iface setting if no longer in auto
- name: setting user WAN fact
  set_fact:
    xsce_wan_iface: "{{ user_wan_iface }}"
  when: user_wan_iface != "auto"

# user disabled interface - overriding all other entries
- name: Checking xsce_lan_enabled
  set_fact:
    user_lan_iface: "none"
  when: 'not xsce_lan_enabled'

# gui wants Appliance Note: could of used xsce_lan_enabled false
- name: Setting GUI wants Appliance
  set_fact:
    user_lan_iface: "none"
  when: gui_desired_network_role is defined and gui_desired_network_role == "Appliance"

# gui wants Gateway
- name: Setting GUI wants and has active Gateway
  set_fact:
    user_lan_iface: "auto"
    user_wan_iface: "{{ discovered_wan_iface }}"
  when: gui_desired_network_role is defined and gui_desired_network_role == "Gateway" and discovered_wan_iface != "none" 

# override with user_lan_iface setting if no longer in auto
- name: Setting user LAN fact
  set_fact:
    xsce_lan_iface: "{{ user_lan_iface }}"
  when: 'user_lan_iface != "auto"'

- name: No LAN configured - Appliance mode
  set_fact:
    dansguardian_enabled: False
    squid_enabled: False
    named_enabled: True
    dhcpd_enabled: False
    wondershaper_enabled: False
    xsce_network_mode: "Appliance"
  when: xsce_lan_iface == "none" or user_lan_iface == "none"

- name: LAN configured - LanController mode
  set_fact:
    named_enabled: True
    dhcpd_enabled: True
    dansguardian_enabled: False
    squid_enabled: False
    wondershaper_enabled: False
    xsce_network_mode: "LanController"
  when: xsce_lan_iface != "" and xsce_wan_iface == "none"

- name: LAN configured - Gateway mode
  set_fact:
    named_enabled: True
    dhcpd_enabled: True
    xsce_network_mode: "Gateway"
  when: 'xsce_lan_iface != "none" and xsce_wan_iface != "none"'

- name: Add location section to config file
  ini_file: dest='{{ xsce_config_file }}'
            section=network
            option='{{ item.option }}'
            value='{{ item.value }}'
  with_items:
  - option: 'wan_enabled'
    value: '{{ xsce_wan_enabled }}'
  - option: 'user_gateway'
    value: '{{ user_wan_iface }}'
  - option: 'computed_gateway'
    value: '{{ xsce_wan_iface }}'
  - option: 'lan_enabled'
    value: '{{ xsce_lan_enabled }}'
  - option: 'user_lan'
    value: '{{ user_lan_iface }}'
  - option: 'computed_lan'
    value: '{{ xsce_lan_iface }}'
  - option: 'xsce_network_mode_applied'
    value: '{{ xsce_network_mode }}'
