- name: Disable firewalld service
  service: name=firewalld
           state=stopped

- name: Install iptables service package
  yum: name=iptables-services
       state=installed
  tags:
    - download

- name: Install iptables services
  template: backup=yes
            src={{ item.src }}
            dest={{ item.dest }}
            owner=root
            group=root
            mode=0755
  with_items:
    - { src: "gateway/iptables-xs.j2" , dest: "/etc/sysconfig/olpc-scripts/iptables-xs" }
    - { src: "gateway/ip6tables-xs" , dest: "/etc/sysconfig/olpc-scripts/ip6tables-xs" }
    - { src: "gateway/iptables-config" , dest: "/etc/sysconfig/iptables-config" }
    - { src: "gateway/iptables.service" , dest: "/etc/systemd/system/iptables.service" }
    - { src: "gateway/xs-gen-iptables" , dest: "/usr/bin/xs-gen-iptables" }
