- name: Disable firewalld service
  service: name=firewalld
           state=stopped
  ignore_errors: yes

- name: Remove iptables.service file from /etc
  file: path=/etc/systemd/system/iptables.service 
        state=absent

- name: Remove iptables-xs.service file from /etc
  file: path=/etc/systemd/system/iptables-xs.service 
        state=absent

- name: Install iptables service package
  yum: name=iptables-services
       state=installed
  tags:
    - download

- name: Install iptables services
  template: backup=yes
            src={{ item.src }}
            dest={{ item.dest }}
            owner=root
            group=root
            mode=0755
  with_items:
    - { src: "gateway/iptables-config" , dest: "/etc/sysconfig/iptables-config" }
    - { src: "gateway/xs-gen-iptables" , dest: "/usr/bin/xs-gen-iptables" }
