- name: Install squid packages
  yum: name={{ item }}
       state=installed
  with_items:
    - squid
    - cadaver
    - dansguardian
  tags:
    - download

- name: Copy init script and config file
  template: src={{ item.src }}
            dest={{ item.dest }}
            owner={{ item.owner }}
            group={{ item.owner }}
            mode={{ item.mode }}
  with_items:
    - src: 'squid/squid.sysconfig'
      dest: '/etc/sysconfig/squid'
      owner: 'root'
      group: 'root'
      mode: '0755'
    - src: 'squid/sites.whitelist.txt'
      dest: '/etc/squid/sites.whitelist.txt'
      owner: 'squid'
      group: 'squid'
      mode: '0644'         
    - src: 'squid/allowregex.rules'
      dest: '/etc/squid/allowregex.rules'
      owner: 'squid'
      group: 'squid'
      mode: '0644'         
    - src: 'squid/denyregex.rules'
      dest: '/etc/squid/denyregex.rules'
      owner: 'squid'
      group: 'squid'
      mode: '0644'         
    - src: 'squid/dstaddress.rules'
      dest: '/etc/squid/dstaddress.rules'
      owner: 'squid'
      group: 'squid'
      mode: '0644'         
    - src: 'squid/dansguardian.conf.j2'
      dest: '/etc/dansguardian/dansguardian.conf'
      owner: 'dansguardian'
      group: 'dansguardian'
      mode: '0640'
    - src: 'squid/xs-httpcache.j2'
      dest: '/usr/bin/xs-httpcache'
      owner: 'root'
      group: 'root'
      mode: '0755'

- name: Create squid cache directory
  file: path=/library/cache
        owner=squid
        group=squid
        mode=0750
        state=directory

- name: Create squid log directory
  file: path=/var/log/squid
        owner=squid
        group=squid
        mode=0750
        state=directory

- name: Create dansguardian log directory
  file: path=/var/log/dansguardian
        owner=dansguardian
        group=dansguardian
        mode=0750
        state=directory

- name: Stop Squid
  service: name=squid
           state=stopped
  ignore_errors: yes
