- name: Install custom profile file
  template: dest=/etc/profile.d/zzz_xsce.sh
            src=zzz_xsce.sh
            owner=root
            mode=0644
            backup=yes

- name: Create /etc/xsce
  file: path=/library
        owner=root
        group=root
        mode=0755
        state=directory

- name: Create xsce.conf file
  template: backup=yes
            src=xsce.conf.j2
            dest=/etc/xsce/xsce.conf
            owner=root
            group=root
            mode=0744
                    
- name: Create /library
  file: path=/library
        owner=root
        group=root
        mode=0755
        state=directory

- name: Disable root login with password 
  lineinfile: backup=yes
              dest=/etc/ssh/sshd_config
              regexp='^PermitRootLogin'
              line='PermitRootLogin without-password'
              state=present
#TODO: use handler to reload ssh

- name: Enable common services
  service: name={{ item }}
           enabled=yes
           state=restarted
  with_items:
    - sshd
