- name: Keep yum cache
  ini_file: dest=/etc/yum.conf
            section=main
            option=keepcache
            value=1

- name: Install common packages
  yum: name={{ item }}
       state=present
  with_items:
   - createrepo
   - acpid
   - mlocate
   - mtd-utils
   - rsync
   - htop
   - etckeeper
   - python-passlib
   - usbmount
   - net-tools
   - openssh-server
   - sudo
   - syslog
   - logrotate
   - xml-common
   - etckeeper
   - make
   - yum-utils
   - tar
   - unzip
   - bzip2
  tags:
    - download

- name: Update common packages
  yum: name={{ item }}
       state=latest
  with_items:
   - bash
   - iptables
   - NetworkManager
   - vim-minimal # ejabberd erlang does not update this properly
  tags:
    - download

