- name: install yum if it has been dropped from our distribution -- Fedora 22 uses dnf!!!
  shell: dnf install -y yum
  when: ansible_distribution == "Fedora" and ansible_distribution_version|int >= 22

- name: Install common packages
  yum: name={{ item }}
       state=present
  with_items:
   - createrepo
   - acpid
   - mlocate
   - rsync
   - htop
   - etckeeper
   - python-passlib
   - usbmount
   - net-tools
   - openssh-server
   - sudo
   - syslog
   - logrotate
   - xml-common
   - make
   - yum-utils
   - tar
   - unzip
   - bzip2
   - i2c-tools
   - bridge-utils
   - usbutils
   - hostapd
   - wpa_supplicant
   - wget
   - openssl   #FC 18 does not supply, but pear requires
  tags:
    - download

- name: Update common packages
  yum: name={{ item }}
       state=latest
  with_items:
   - NetworkManager
   - bash
   - iptables
   - vim-minimal # ejabberd erlang does not update this properly
   - dbus-glib   # NM does not update this properly
  tags:
    - download

