- name: Install common packages
  yum: name={{ item }}
       state=present
  with_items:
   - createrepo
   - acpid
   - mlocate
   - rsync
   - htop
   - etckeeper
   - python-passlib
   - usbmount
   - net-tools
   - openssh-server
   - sudo
   - syslog
   - logrotate
   - xml-common
   - make
   - yum-utils
   - tar
   - unzip
   - bzip2
   - i2c-tools
   - bridge-utils
   - usbutils
   - hostapd
   - wpa_supplicant
  tags:
    - download

- name: Update common packages
  yum: name={{ item }}
       state=latest
  with_items:
   - bash
   - iptables
   - vim-minimal # ejabberd erlang does not update this properly
  tags:
    - download

