    - name: Install MySQL
      yum: name={{ item }}
      with_items:
        - MySQL-python
        - mysql
        - mysql-server

    - name: Start the MySQL service
      service: name=mysqld state=started

# 'localhost' needs to be the last item for idempotency, see
# http://ansible.cc/docs/modules.html#mysql-user
    - name: update mysql root password for all root accounts
      mysql_user: name=root host={{ item }}  password={{ mysql_root_password }}
      with_items:
        - {{ ansible_hostname }}
        - 127.0.0.1
        - ::1
        - localhost

    - name: copy .my.cnf file with root password credentials
      template: src=templates/root/my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

    - name: delete anonymous MySQL server user for {{ server_hostname }}
      mysql_user: user="" host="{{ server_hostname }}" state="absent"

    - name: delete anonymous MySQL server user for localhost
      mysql_user: user="" state="absent"

    - name: remove the MySQL test database
      mysql_db: db=test state=absent
