    - name: Install MySQL
      yum: name={{ item }}
      with_items:
        - MySQL-python
        - mysql
        - php-mysql
        - php-gd
        - php-imap
        - php-ldap
        - php-odbc
        - php-pear
        - php-xml
        - php-xmlrpc
      tags:
        - download

    - include: centos.yml
      when: ansible_distribution == "CentOS"
      tags:
        - download

    - include: fedora.yml
      when: ansible_distribution == "Fedora"
      tags:
        - download

# Name of mysql service varies by OS so softcoded in 1-prep
    - name: Start the MySQL service
      service: name={{ mysql_service }}
               state=started

    - name: Enable the MySQL service
      service: name={{ mysql_service }}
               enabled=yes
      when: mysql_enabled

# 'localhost' needs to be the last item for idempotency, see
# http://ansible.cc/docs/modules.html#mysql-user
# unfortunately it still doesn't work
    - name: update mysql root password for localhost root accounts
      mysql_user: name=root host={{ item }}  password={{ mysql_root_password }} priv=*.*:ALL,GRANT
      with_items:
        - localhost
      when: mysql_enabled

    - name: copy .my.cnf file with root password credentials
      template: src=my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600
      when: mysql_enabled

    - name: update mysql root password for all remaining root accounts
      mysql_user: name=root host={{ item }}  password={{ mysql_root_password }} priv=*.*:ALL,GRANT
      with_items:
        - "{{ xsce_hostname }}.{{ xsce_domain }}"
        - 127.0.0.1
        - ::1
      when: mysql_enabled

    - name: delete anonymous MySQL server user for {{ ansible_hostname }}
      mysql_user: user="" host="{{ ansible_hostname }}" state="absent"
      when: mysql_enabled

    - name: delete anonymous MySQL server user for localhost
      mysql_user: user="" state="absent"
      when: mysql_enabled

    - name: remove the MySQL test database
      mysql_db: db=test state=absent
      when: mysql_enabled

    - name: Set the php default date, so it does not complain
      lineinfile: line="date.timezone = {{ local_tz }}" dest=/etc/php.ini

    - name: Get the phpmyadmin software
      get_url: url="{{ xsce_download_url }}/{{ phpMyAdmin }}"  dest="{{ downloads_dir}}/phpMyAdmin.zip"
      when: not {{ use_cache }} and not {{ no_network }}
      tags:
        - download2

    - name: Copy it to permanent location /opt
      unarchive: src={{ downloads_dir }}/phpMyAdmin.zip  dest=/opt/

    - name: Create a symbolic link to the folder of the current version phpmyadmin
      file: path=/opt/phpmyadmin src=phpMyAdmin-4.2.7.1-all-languages state=link

    - name: Put the alias into Apache config
      template: src=phpmyadmin.j2 dest=/etc/httpd/conf.d/phpmyadmin.conf
      when: mysql_enabled

    - name: Copy the phpmyadmin config file into place
      template: src=config.inc.php dest=/opt/phpmyadmin/config.inc.php
      when: mysql_enabled

    - name: Change the owner of the php tree to apache
      shell: "chown -R apache /opt/phpmyadmin"
      when: mysql_enabled

    - name: add mysql to service list
      ini_file: dest='{{ service_filelist }}'
                    section=mysql
                    option='{{ item.option }}'
                    value='"{{ item.value }}"'
      with_items:
            - option: name
              value: mysql-database
            - option: description
              value: "mySQL is a widely used database service on the Internet which runs on many platforms, and is often offered and available at hosting Internet Service Providers"
            - option: enabled
              value: "{{ mysql_enabled }}"

    - name: Initially mysql and phpmyadmin were enabled together -- work to separate them -- then delete this
      set_fact: phpmyadmin_enabled='{{ mysql_enabled }}'

    - name: add phpmyadmin to service list
      ini_file: dest='{{ service_filelist }}'
                    section=phpmyadmin
                    option='{{ item.option }}'
                    value='"{{ item.value }}"'
      with_items:
            - option: name
              value: phpMyAdmin
            - option: description
              value: "phpMyAdmin is an interface with a mysql database written in php, and available to administer the database engine locally or across the network"
            - option: path
              value: /opt/phpmyadmin
# TODO (maybe?) separately enable phpmyadmin in GUI (and disable the set fact above
            - option: enabled
              value: "{{ phpmyadmin_enabled }}"
