xsce_base_ver: 2
gui_version: 1

NUC6_firmware_needed: False
is_F18: False
is_F20: False
is_F21: False
is_F22: False
is_F23: False
is_F24: False
udev_needs_patch: False
installing: True
xsce_lan_iface: "none"
xsce_wan_iface: "none"
gui_port: 80
xsce_prepped: False
# must keep roles/xsce-admin/defaults/main.yml sync'd
admin_console_path: "{{ xsce_base }}/admin_console"
cmdsrv_path: "{{ xsce_base }}/xsce_cmdsrv"
xsce_cmdsrv_dbname : "xsce_cmdsrv.0.2.db"
wifi_id: none
