# Keep in sync with 1-prep
new_base_ver: 3

# must keep roles/xsce-admin/defaults/main.yml sync'd
admin_console_path: "{{ xsce_base }}/admin_console"
cmdsrv_path: "{{ xsce_base }}/xsce_cmdsrv"
xsce_cmdsrv_dbname : "xsce_cmdsrv.0.2.db"

is_F18: False
is_F20: False
is_F21: False
is_F22: False
is_F23: False
is_F24: False
is_F25: False
ansbile1: True

installing: True

NUC6_firmware_needed: False
udev_needs_patch: False
xsce_lan_iface: "none"
xsce_wan_iface: "none"
gui_port: 80
xsce_prepped: False
wifi_id: none

wondershaper_dspeed: "4096"
wondershaper_upspeed: "1024"
