- name: Base Server Installed
  command: echo Base Server Installed

- name: Restart xsce-cmdsrv service
  service: name=xsce-cmdsrv
           state=restarted
  when: not installing

- name: Restart httpd
  service: name=httpd
           state=restarted
  when: not installing

- name: Create hidden xsce-prepped file
  file: dest=/.xsce-prepped
        state=touch
