- name: install wondershaper ajenti plugin
  pip: name=https://github.com/migonzalvar/ajenti-plugin-wondershaper/archive/0.3.tar.gz

- name: restart ajenti service
  service: name=ajenti
           state=restarted
