- name: Create httpd config files
  template: backup=yes
            src={{ item.src }}
            dest={{ item.dest }}
            owner=root
            group=root
            mode={{ item.mode }}
  with_items:
     - { src: '010-xsce.conf.j2' , dest: '/etc/httpd/conf.d/010-xsce.conf', mode: '0755' }
     - { src: 'proxy_ajp.conf.j2' , dest: '/etc/httpd/conf.d/proxy_ajp.conf', mode: '0644' }
     - { src: 'php.ini.j2' , dest: '/etc/php.ini' , mode: '0644' }
     - { src: 'xs-console.conf.j2' , dest: '/etc/httpd/conf.d/xs-console.conf', mode: '0644' }

- name: Remove old config file
  file: path=/etc/httpd/conf.d/xs-2.4.conf
        state=absent

- name: Create http pid dir
  file: path=/var/run/httpd
        mode=0755
        owner=root
        group=root
        state=directory

- name: Create httpd log dir
  file: path=/var/log/httpd
        mode=0755
        owner=apache
        group=apache
        state=directory

- name: Create admin group
  group: name=admin
         state=present

- name: Add apache user to admin group
  user: name=apache
        groups=admin
        state=present
        createhome=no

- name: Enable httpd
  service: name=httpd
           enabled=yes

