dependencies:
   - { role: mysql, tags: ['generic','mysql'], when: mysql_install }
   - { role: elgg, tags: ['generic','elgg'], when: elgg_install }
   - { role: owncloud, tags: ['generic','owncloud'], when: owncloud_install }
   - { role: dokuwiki, tags: ['generic','dokuwiki'], when: dokuwiki_install }
