- name: Set hostname
  template: backup=yes
            dest=/etc/hostname
            src=hostname.j2
            owner=root
            mode=0644

- name: Install xsce-release and xsce-extra repos
  get_url: url={{ item }} dest=/etc/yum.repos.d/
  tags:
    - download
  with_items:
    - http://xsce.activitycentral.com/repos/xsce-release.repo
    - http://xsce.activitycentral.com/repos/xsce-extra.repo

- include: xo.yml
  when: ansible_distribution_release == "based on Fedora 18"
  tags:
    - xo

- include: selinux.yml
  when: ansible_selinux["status"] != "disabled"
  tags:
    - download

- name: Install custom profile file
  template: dest=/etc/profile.d/zzz_xsce.sh
            src=zzz_xsce.sh
            owner=root
            mode=0644
            backup=yes

- name: Create /library
  file: path=/library
        owner=root
        group=root
        mode=0755
        state=directory

- name: Disable root login with password 
  lineinfile: backup=yes
              dest=/etc/ssh/sshd_config
              regexp='^PermitRootLogin'
              line='PermitRootLogin without-password'
              state=present
#TODO: use handler to reload ssh

- name: Enable common services
  service: name={{ item }}
           enabled=yes
           state=restarted
  with_items:
    - sshd


- include: yum.yml 
  tags:
    - download

- include: chrony.yml
- include: avahi.yml
- include: sysctl.yml
