- name: Get XSCE facts
  xsce_facts: facts=true
  tags: 
    - facts
    - common
    - gateway
    - dhcpd
    - network
    - ajenti
    - wondershaper
    - core
    - xo
    - download

- name: Set hostname
  template: backup=yes
            dest=/etc/hostname
            src=hostname.j2
            owner=root
            mode=0644

- name: Install xs repo
  get_url: url=http://xsce.activitycentral.com/repos/xsce-release.repo dest=/etc/yum.repos.d/
  tags:
    - download

- include: xo.yml
  when: ansible_distribution_release == "based on Fedora 18"
  tags:
    - xo

- include: selinux.yml
  when: ansible_selinux["status"] != "disabled"
  tags:
    - download

- name: Create /library
  file: path=/library
        owner=root
        group=root
        mode=0755
        state=directory

- name: Disable root login with password 
  lineinfile: backup=yes
              dest=/etc/ssh/sshd_config
              regexp='^PermitRootLogin'
              line='PermitRootLogin without-password'
              state=present
#TODO: use handler to reload ssh

- name: Enable common services
  service: name={{ item }}
           enabled=yes
           state=restarted
  with_items:
    - sshd


- include: yum.yml 
  tags:
    - download

- include: chrony.yml
- include: avahi.yml
- include: sysctl.yml
