- name: Install packages for console
  package: name={{ item }}
           state=installed
  with_items:
    - mod_ssl
    - mod_authnz_external
    - pwauth
  tags:
    - download

- name: Create admin-console directory tree
  file: path={{ item }}
        mode=0755
        owner=root
        group=root
        state=directory
  with_items:
    - "{{ admin_console_path }}"
    - "{{ admin_console_path }}/css"
    - "{{ admin_console_path }}/help"
    - "{{ admin_console_path }}/js"
    - "{{ admin_console_path }}/htmlf"

- name: Copy admin-console css files
  copy: src={{ item }}
        dest="{{ admin_console_path }}/css"
        mode=0644
        owner=root
        group=root
  with_fileglob:
        - console/css/*.css

- name: Copy admin-console help files
  copy: src={{ item }}
        dest="{{ admin_console_path }}/help"
        mode=0644
        owner=root
        group=root
  with_fileglob:
        - console/help/*

- name: Copy admin-console javascript files
  copy: src={{ item }}
        dest="{{ admin_console_path }}/js"
        mode=0644
        owner=root
        group=root
  with_fileglob:
        - console/js/*

- name: Copy admin-console html fragment files
  copy: src={{ item }}
        dest="{{ admin_console_path }}/htmlf"
        mode=0644
        owner=root
        group=root
  with_fileglob:
        - console/htmlf/*

- name: Install admin-console config file
  template: src=console/xs-console.conf.j2
            dest=/etc/httpd/conf.d/xs-console.conf
            owner=root
            group=root
            mode=0644
  when: not adm_cons_force_ssl

- name: Install admin-console config file with ssl support
  template: src=console/xs-console-ssl.conf.j2
            dest=/etc/httpd/conf.d/xs-console.conf
            owner=root
            group=root
            mode=0644
  when: adm_cons_force_ssl

- name: Install admin-console command service
  template: src=console/cmd-service.php
            dest="{{ admin_console_path }}/cmd-service.php"
            owner=root
            group=root
            mode=0644

- name: Install admin-console server info service
  template: src=console/server-info.php
            dest="{{ admin_console_path }}/server-info.php"
            owner=root
            group=root
            mode=0644

- name: Install admin-console app
  copy: src=console/index.html
        dest="{{ admin_console_path }}/index.html"
        owner=root
        group=root
        mode=0644
