rachel_url: /rachel
rachel_doc_root: /var/www/html{{ rachel_url }}
rachel_content_path: /library/rachel/www/
rachel_mysqldb_path: /library/rachel/bin/database/mysql-5.6.20/data/sphider_plus/

# These two must be in sync, second saves parsing
rachel_src_url: http://rachelfriends.org/rachelusb_32EN/rachelusb_32EN_3.1.5.zip
rachel_version: rachelusb_32EN_3.1.5

rachel_install: True
rachel_enabled: False
rachel_content_found: False
